[profile.default]
src = "src"
unchecked_cheatcode_artifacts = true # To solve the vm.getCode(): Artifact not found issue
out = "out"
libs = ["lib"]

remappings = [
    "@uniswap/v2-core/contracts/=lib/v2-core/contracts/",
    "@uniswap/v2-periphery/contracts/=lib/v2-periphery/contracts/",
    "@uniswap/lib/contracts/=lib/solidity-lib/contracts/"
]

auto_detect_solc = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/F4e5AaB8g2gfoo2Faz4jX"
arbitrum_sepolia = "https://arb-sepolia.g.alchemy.com/v2/F4e5AaB8g2gfoo2Faz4jX"



[etherscan]
arbitrum_sepolia = { key = "RIZ5C9K5V9I5Q8XJ3FJ5MD1PG1IE7IU23E" }

