[profile.default]
optimizer = true
optimizer_runs = 800
bytecode_hash = "none"
src = "src"
unchecked_cheatcode_artifacts = true # To solve the vm.getCode(): Artifact not found issue
out = "out"
via_ir = false  # Disable IR to compile 0.6/0.7 libs (OZ 3.x)
libs = ["lib"]
libraries = [
    "@uniswap/v3-periphery/contracts/libraries/NFTDescriptor.sol:NFTDescriptor:0x42B24A95702b9986e82d421cC3568932790A48Ec"
]
remappings = [
    "@uniswap/v2-core/contracts/=lib/v2-core/contracts/",
    "@uniswap/v2-periphery/contracts/=lib/v2-periphery/contracts/",
    "@uniswap/lib/contracts/=lib/solidity-lib/contracts/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/swap-router-contracts/=lib/swap-router-contracts/",
    "@uniV3_OZ/=lib/openzipplin_3.4.2_uniswapV3/",
    "base64-sol/=lib/base64/",
    "@OZ_3.4.0/=lib/openzipplin_3.4.0_uniswapV3/",
    "@OZ_3.4.1/=lib/openzipplin_3.4.1_uniswapV3/",
    "@OZ_4.0.0/=lib/openzipplin_4.0.0_uniswapV3/"
]

# Allow Foundry to use multiple solc versions per pragma
auto_detect_solc = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
arbitrum = "https://arb-mainnet.g.alchemy.com/v2/F4e5AaB8g2gfoo2Faz4jX"
arbitrum_sepolia = "https://arb-sepolia.g.alchemy.com/v2/F4e5AaB8g2gfoo2Faz4jX"



[etherscan]
arbitrum_sepolia = { key = "RIZ5C9K5V9I5Q8XJ3FJ5MD1PG1IE7IU23E" }


